#!/bin/bash

USERNAME=sathyamvellal
REPO_NAME=sathyamvellal.github.io
REPO_URL=git@github.com:$USERNAME/$REPO_NAME.git
BUILD_DIR=_site
DEPLOY_BRANCH=master

# clear build_dir
cd $BUILD_DIR
rm -rf ./*
cd ..

# build
echo "Building..."
gulp
echo "Building... done!"
