#!/bin/bash

USERNAME=sathyamvellal
REPO_NAME=sathyamvellal.github.io
REPO_URL=git@github.com:$USERNAME/$REPO_NAME.git
BUILD_DIR=_site
DEPLOY_BRANCH=master

# deploy
echo "Deploying..."
cd $BUILD_DIR
git add .
git commit -m "Site update"
git push "$REPO_URL" $DEPLOY_BRANCH --force
cd ..
echo "Deploying... done!"